### ISSUE TITLE
Bug: APIGatewayHttpResolver with validation enabled returns HTTP 422 when using single value query parameters

### ISSUE THREAD

**Issue by DariusKunce** [awslabs/aws-lambda-powertools-python#3732] opened 2024-02-07 16:12 UTC
### Expected Behaviour

When using Amazon Api Gateway REST API to invoke an AWS Lambda using proxy integration, calling API with a single query parameter should return HTTP 200 with Lambda Powertools validation enabled. 

This is also how it is documented here: https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/api_gateway/#validating-query-strings

### Current Behaviour

Calling API with `GET /my-path?productType=Category1` returns HTTP 422:
```json
{
    "statusCode": 422,
    "detail": [{
        "loc": ["query", "productType"], 
        "type": "type_error.str"
    }]
}
```

### Code snippet

```python
Bug can be reproduced with this code inside a Lambda function:


app = api_gateway.APIGatewayRestResolver(
    enable_validation=True
)

@app.get("/my-path")
def my_handler(
    product_type: Annotated[str | None, Query(alias="productType")] = None,
) -> api_gateway.Response[api_model.GetAvailableProductsResponse]:
    ...
```

### Possible Solution

Can be fixed by changing query param type to list:

```python
@app.get("/my-path")
def my_handler(
    product_type: Annotated[list[str] | None, Query(alias="productType")] = None,
) -> api_gateway.Response[api_model.GetAvailableProductsResponse]:
    """Lists available products"""
    ...
```

### Steps to Reproduce

In AWS:
1. Create a REST API in the Amazon Api Gateway Service.
2. Create a Lambda function with Lambda Powertools configured as in the code examples.
3. Configure the API Gateway with proxy integration to the Lambda function.
4. Invoke the API with a query parameter.

Locally:
1. Create unit tests for a Lambda function as described here: https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/api_gateway/#testing-your-code
2. Run the test using REST API proxy integration payload. This payload always contains 2 attributes for the query string parameters, regardless if it's single value or multi value in REST API proxy integration:
    ```json
    {
        ...
        "queryStringParameters": { "productType": "Category1" },
        "multiValueQueryStringParameters": { "productType": ["Category1"] }
    }
    ```

The issue is this line of code: https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py#L123 

Lambda Powertools should additionally check dictionary values in `multiValueQueryStringParameters` if they contain only one value, and validate accordingly to be of type `str` instead of `list[str]`.

### Powertools for AWS Lambda (Python) version

2.33.0

### AWS Lambda function runtime

3.12

### Packaging format used

PyPi

**Comment by sthulb** [comment] 2024-02-08 16:22
Hi @DariusKunce this is on my list for verification tomorrow, thanks for submitting it!

**Comment by sthulb** [comment] 2024-02-09 10:43
@DariusKunce Confirmed! We'll add this into the next sprint to fix

```python
def test_weird_issue():
    # GIVEN a Http API V2 proxy type event
    app = APIGatewayRestResolver(enable_validation=True)

    class FunkyTown(BaseModel):
        parameter: str

    @app.get("/my/path")
    def my_path(
        parameter: Annotated[str | None, Query(alias="parameter1")] = None,
    ) -> Response[FunkyTown]:
        assert isinstance(app.current_event, APIGatewayProxyEvent)

        assert parameter == "value"
        return Response(200, content_types.APPLICATION_JSON, FunkyTown(parameter=parameter))

    result = app(load_event("apiGatewayProxyEvent.json"), {})

    print(result)
    assert result["statusCode"] == 200
```

**Comment by heitorlessa** [comment] 2024-02-15 09:01
@DariusKunce we're aiming to make a release tomorrow with this fix ahead of schedule -- let us know if you're blocked by this and we can make it today.

**Comment by jpoissant** [comment] 2024-02-15 18:49
The issue isn't related to the alias but the fact that the `openapi_validation.py` handles all query strings with `_normalize_multi_query_string_with_param` and takes the first value of the item.

With `"queryStringParameters": { "productType": "Category1" }` it's normalize to: `"productType": "C"`

With `"multiValueQueryStringParameters": { "productType": ["Category1"] }` it's normalize correctly to: `"productType": "Category1"`

I was able to find this as I was trying to validate the min length of a query string parameter (`def get_hello(fname: Annotated[Optional[str], Query(min_length=4)] = None) -> HelloWorld:` and `fname` was always too short... as it was always truncated to 1 character.


The line truncating the value is [here](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/event_handler/middlewares/openapi_validation.py#L391)

**Comment by heitorlessa** [comment] 2024-02-15 22:14
Thanks a lot for the timely comment @jpoissant.

@rubenfonseca i think we had mixed messaging and this wasn't fixed -- if you can't look into it tomorrow morning before release, let me know pretty plz

**Comment by rubenfonseca** [comment] 2024-02-16 10:02
Thank you so much @jpoissant I'm looking at this right now

**Comment by rubenfonseca** [comment] 2024-02-16 10:16
> The issue isn't related to the alias but the fact that the `openapi_validation.py` handles all query strings with `_normalize_multi_query_string_with_param` and takes the first value of the item.
> 
> With `"queryStringParameters": { "productType": "Category1" }` it's normalize to: `"productType": "C"`
> 
> With `"multiValueQueryStringParameters": { "productType": ["Category1"] }` it's normalize correctly to: `"productType": "Category1"`

@jpoissant I need to understand the problem a little bit better, since I'm unable to reproduce the problem. Can you please confirm which event handler are you using? Is it the APIGatewayRestResolver ?

Reason I'm asking is that the [REST API Gateway will always send `multiValueQueryStringParameters`](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format), so the existing code already works correctly.

So I need to understand what scenario do you have where you only have `queryStringParameters`. Can you please clarify?

**Comment by jpoissant** [comment] 2024-02-16 15:55
@rubenfonseca I am using the `APIGatewayHttpResolver` resolver. I just tried with the `APIGatewayRestResolver` and it work. So the bug is only related to the API Gateway v2 proxy payload format

**Comment by jpoissant** [comment] 2024-02-16 21:35
@rubenfonseca would it be better to open a new bug for the `APIGatewayHttpResolver` resolver?

**Comment by rubenfonseca** [comment] 2024-02-19 09:05
No that helps, let me investigate today and I'll get back to you today!

**Comment by rubenfonseca** [comment] 2024-02-19 10:16
Got it, was able to reproduce the problem! Fix incoming

**Comment by heitorlessa** [comment] 2024-02-19 16:34
Coming up in this week's release! Just merged Ruben's PR

**Comment by heitorlessa** [comment] 2024-02-20 09:35
We're making a release today after we push a non-related and last bugfix for this release 🚀

**Closed as completed** 2024-02-21 08:34 UTC
Labels: bug
