### ISSUE TITLE
Feature request: improve error messaging around IdempotencyPersistenceLayerError

### ISSUE THREAD

**Issue by cgoettel** [awslabs/aws-lambda-powertools-python#1772] opened 2022-12-09 22:38 UTC
### Use case

I was trying to implement the basic example using Terraform to deploy the Lambda and DynamoDB. However, I had forgotten to include the policy for the Lambda to talk to DynamoDB and kept getting the following error:

```
[ERROR] IdempotencyPersistenceLayerError: Failed to save in progress record to idempotency store
Traceback (most recent call last):
  File "/var/task/aws_lambda_powertools/middleware_factory/factory.py", line 134, in wrapper
    response = middleware()
  File "/var/task/aws_lambda_powertools/utilities/idempotency/idempotency.py", line 79, in idempotent
    return idempotency_handler.handle()
  File "/var/task/aws_lambda_powertools/utilities/idempotency/base.py", line 97, in handle
    return self._process_idempotency()
  File "/var/task/aws_lambda_powertools/utilities/idempotency/base.py", line 116, in _process_idempotency
    raise IdempotencyPersistenceLayerError("Failed to save in progress record to idempotency store") from exc
```

Each error message is the same which isn't entirely helpful. So I dug through the code and could see that it was exception chaining, but that also wasn't particularly helpful. It wasn't until I tried to implement the basic example using AWS SAM that I was able to see the policy that I'd forgotten to attach.

### Solution/User Experience

Ideally, something in the error chain would receive a bad permissions error and that information would percolate up to the user. Every other time I deploy into AWS I get clear permissions errors and the reason I didn't even consider a permissions issue is because it was always so clear previously when that was it.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by mploski** [comment] 2022-12-13 11:30
Hey @cgoettel, thanks for raising this issue. I agree we need to enrich the error message here to be more meaningful. I will start working on this in a few coming days (probably end of the week or beginning of the next one). Will update you about the progress

**Comment by mploski** [comment] 2022-12-20 16:43
Hey @cgoettel. I was able to reproduce mentioned issue and I can confirm your observation, that lambda emits logs in the shape you shared in the ticket itself. Let me share some details about it, just for future reference or interested readers :-)

 In idempotency feature we rely on “raise from” statement to raise an exception with extra information whenever we have problem. That works if I trigger handler code directly from my local environment (not from lambda).  Then we get chained traces like in the following snippet:  
```
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x11324b520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
 ....
 
During handling of the above exception, another exception occurred:

 raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: 
...
The above exception was the direct cause of the following exception: 
...
aws_lambda_powertools.utilities.idempotency.exceptions.IdempotencyPersistenceLayerError: Failed to save in progress record to idempotency store 
```

  Lambda runtime behaves differently though. In a runtime bootstrap action we modify logging behavior. 
  We do multiple different actions there, but for our case what's important is that exceptions not handled gracefully in handler itself are managed by another exception block. This block is responsible for extracting an exception and traceback, formatting message and sending it to a stdout. Specifically, we use `sys.exc_info()` function to extract raised exception. It also means we skip all other nested exceptions as they are not returned by `exc_info()` function. That's why we cannot see them in Cloudwatch logs.
  
  If you are interested in details please take a look at a lambda runtime bootstrap code: https://github.com/aws/aws-lambda-python-runtime-interface-client/blob/970e9c1d2613e0ce9c388547c76ac30992ad0e96/awslambdaric/bootstrap.py#L157
  
  I will work on exposing additional context from nested exceptions to make it visible in CloudWatch Logs.

**Comment by mploski** [comment] 2023-01-09 14:42
hey @cgoettel, we just merged changes to the Idempotency feature, that will improve error messaging and hopefully will simplify debugging or reasoning about potential issues in future. Thank you one more time for the contribution and making Lambda Powertools better :-)

**Closed as completed** 2023-01-12 09:57 UTC
Labels: feature-request, idempotency

**Comment by mattyweb** [comment] 2023-02-05 23:27
Lifesaver! Thanks!

Just found this thread and upgraded to the new PowerTools in order to troubleshoot. Trying an idempotent lambda in python and this was my first time using DynamoDB.

Had to add the following actions to my lambda config:
            "Action": [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:UpdateItem",
                "dynamodb:DeleteItem"
            ],

Don't know how I would have figured this out otherwise. Might be good to add this to the PowerTools Idempotency docs! (Unless I just missed it!)

**Comment by heitorlessa** [comment] 2023-02-06 06:13
We somehow missed it in the docs 😳!  Apologies from the team.

We always add within getting started—>required resources, with an IAM
section when needed. For Idempotency docs, we added in the sample SAM
template under Policies — however, we missed a dedicated section since we
know not everyone uses SAM

If someone wants to make their first PR, please feel free to do so and we
can help with the wording - otherwise we’ll get it done this week.

https://awslabs.github.io/aws-lambda-powertools-python/2.7.1/utilities/idempotency/#required-resources

**Comment by heitorlessa** [comment] 2023-02-07 08:51
@mattyweb we've just patched the live documentation with the IAM section for Idempotency - took us slightly longer to avoid leaking new features coming in the next release.

https://awslabs.github.io/aws-lambda-powertools-python/2.7.1/utilities/idempotency/#iam-permissions

Thank you again for flagging this!

**Comment by mattyweb** [comment] 2023-04-07 01:09
Totally missed the update here. Thanks so much for the doc fix!
