### ISSUE TITLE
Bug: Logger is not defined

### ISSUE THREAD

**Issue by macdrorepo** [awslabs/aws-lambda-powertools-python#1275] opened 2022-07-01 21:38 UTC
### Expected Behaviour

Logger to be used as always have been (same usagee as in below code snippet done in dozens of other lambdas)

### Current Behaviour

Error from Lambda logs:
`[ERROR] NameError: name 'Logger' is not defined Traceback (most recent call last):   File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 850, in exec_module   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed   File "/var/task/lambda.py", line 11, in <module>     LOGGER = Logger(sampling_rate=float(os.environ["POWERTOOLS_LOGGER_SAMPLE_RATE"]))`

### Code snippet

```python
# -*- coding: utf-8 -*-
"""Stop EC2 with Schedule tag name."""
import os
from typing import Any, Dict

import boto3
from aws_lambda_powertools import Logger
from aws_lambda_powertools.utilities.typing import LambdaContext

LOGGER = Logger(sampling_rate=float(os.environ["POWERTOOLS_LOGGER_SAMPLE_RATE"]))
REGION = os.environ["REGION"]
TAG_NAME = os.environ["TAG_NAME"]
TAG_VALUE = os.environ["TAG_VALUE"]
FILTERS = [{"Name": f"tag:{TAG_NAME}", "Values": [TAG_VALUE]}]
CLIENT = boto3.client("ec2", region_name=REGION)


# pylint: disable=W0613
@LOGGER.inject_lambda_context(log_event=True)
def lambda_handler(event: Dict[str, Any], context: LambdaContext) -> None:
    """Starting lambda."""
    LOGGER.debug(f"Event: {event}")

    reservations = CLIENT.describe_instances(Filters=FILTERS)
    for r in reservations["Reservations"]:
        for i in r["Instances"]:
            CLIENT.stop_instances(InstanceIds=[i["InstanceId"]])
            LOGGER.debug(f"Stopped {i['InstanceId']} successfully")
```

### Steps to Reproduce

Deploy powertools 1.26.1 to lambda layer, lambda code to lambda service

### AWS Lambda Powertools for Python version

1.26.1

### AWS Lambda function runtime

3.9

### Packaging format used

Lambda Layers

**Comment by heitorlessa** [comment] 2022-07-02 09:58
Hey @macdrorepo, could you share your build and deployment process?

Are you building your own Lambda Layer? Or are you using our public layers?

The error suggests that the package is empty, as in no packages inside aws_lambda_powertools.

I've just used the latest Lambda Layer (21) and it worked as expected. I've also created my own Lambda Layer using SAM CLI and it worked - tho I used the latest version (1.26.2), should work regardless.

https://awslabs.github.io/aws-lambda-powertools-python/latest/#install

https://github.com/heitorlessa/rotterdam-pt/blob/f06ae699b52a930a2d024f68479eab4c7982fb15/sample_api/template.yaml#L47

We'd be more than happy to try and find a solution once we understand more about the process you used.

Thank you!

**Comment by macdrorepo** [comment] 2022-07-02 19:01
Hi,

So I am using cdk pipelines to deploy everything. Have this code to build layer with tools:

```
def create_lambda_layer(
        self, props: Dict, code_path: lmb.Code, runtime_list: Union[lmb.Runtime, List]
    ) -> lmb.LayerVersion:
        return lmb.LayerVersion(
            self,
            "supporting_libraries",
            code=code_path,
            compatible_runtimes=runtime_list,
            description=f"Supporting libs layer for {props['project']}",
        )
```

This is invoking part:

```
lambda_layer = lambda_object.create_lambda_layer(props=props, code_path=layer_code_path, runtime_list=[runtime])
```

Cdk asset being created, and during pipeline execution invoking requirements.txt required libs (including lambda tools) suppose to be installed into layer which is attached to lambda. Same process done many many times before was working like a charm, no idea what happened this time.

**Comment by leandrodamascena** [comment] 2022-07-02 23:29
Hi @macdrorepo, how are you?

I'm also working on a side project where I deploy the infrastructure with CDK and I'm using Lambda Powertools as a layer. If I understand correctly, you are building your own Lambda Powertools layer, right? I imagine you are including other things in this layer as well. In that case, my question is, since the Lambda Powertools project maintains a public and up-to-date layer, why are you building your own Lambda Powertools layer? You can't use the official layer for some reason like signing, code analysis, compliance or other things? If you don't have any kind of restrictions, I think it makes more sense to use the [official layer](https://awslabs.github.io/aws-lambda-powertools-python/latest/#lambda-layer).

I isolated a piece of code where I use CDK to deploy the Lambda function and add the official Lambda Powertools layer. Hope this can help you.

![image](https://user-images.githubusercontent.com/4295173/177018741-90a4fabc-a4a0-4c47-8885-1895f42d046e.png)
![image](https://user-images.githubusercontent.com/4295173/177018769-c454ac33-1d15-410b-b49c-ba3f780f172d.png)
![image](https://user-images.githubusercontent.com/4295173/177018786-666dd2fe-e78b-41e3-b12f-8f04e9d63fc2.png)
![image](https://user-images.githubusercontent.com/4295173/177018794-ca38275e-530b-4f7b-aebd-ae3a38fb57cf.png)

Also, if you want to check which version of Lambda Powertools is deployed on a specific layer tag, you go to the Lambda Console and check that.

![image](https://user-images.githubusercontent.com/4295173/177018849-84deeb2a-da80-4dce-be30-513396449544.png)
![image](https://user-images.githubusercontent.com/4295173/177018854-080fba22-1f81-4525-8e13-ffa7f4b4f193.png)

**Comment by macdrorepo** [comment] 2022-07-04 10:24
@leandrodamascena Thank you. Yes I;m using custom layer. Again it was working for dozen of other projects so had no idea what happened this time. I'll try to redeploy and or use this official layer.

**Comment by heitorlessa** [comment] 2022-07-04 10:29
@macdrorepo try downloading a copy of the immutable Lambda Layer assets you built, it might shed some light on the differences. Here's an example of how to get a S3 Signed URL to fetch the last version of our official Lambda Layer:

> Replace with your custom Lambda Layer ARN

```bash
aws lambda get-layer-version-by-arn --arn arn:aws:lambda:eu-west-1:017000801446:layer:AWSLambdaPowertoolsPython:21  --query 'Content.Location'
```

**Comment by macdrorepo** [comment] 2022-07-04 10:39
@heitorlessa here screenshot, if something more would be needed please let me know.

![image](https://user-images.githubusercontent.com/33083934/177138443-0c6b8f39-6e78-49a4-930a-c2d658c05b51.png)

**Comment by heitorlessa** [comment] 2022-07-04 10:43
could you expand the `logging` module, please? `aws_lambda_powertools/logging`

Also, please share the contents of `aws_lambda_powertools/__init__.py` and `aws_lambda_powertools/logging/__init__.py`.

if it's any easier, feel free to create a zip and attach here as GitHub will automatically upload any file you copy/paste as a gist

**Comment by macdrorepo** [comment] 2022-07-04 10:45
Here you are whole powertools lib content :)

[aws_lambda_powertools.zip](https://github.com/awslabs/aws-lambda-powertools-python/files/9038738/aws_lambda_powertools.zip)

**Comment by heitorlessa** [comment] 2022-07-04 10:52
I admit I have no idea what's going on - I've downloaded your ZIP, modified init to be triple sure it'd execute that code, and it just works as expected. If it wasn't consistent, I'd have guessed that Lambda downloaded a corrupted Layer content - even there I know Lambda has a good checksum mechanism.

How would you like to proceed as we can't reproduce it @macdrorepo?

We also have a CDK Lambda Layer Construct that we also test before publishing it, if it's of any future help - regardless your layer building process is as good as it can get, something edgy happened at the Lambda service.

![image](https://user-images.githubusercontent.com/3340292/177139874-8df08b6d-61ef-468c-ae52-9edaea5aaa84.png)

**Comment by macdrorepo** [comment] 2022-07-04 10:58
Yes i suspect again AWS, as for past few months in their various services we hit some strange errors and issues like this one.
Since lib authors confirmed the code is ok, I'll try to redeploy my own layer or use your "official" one.
Lets close / freeze this for now i think ?

**Comment by heitorlessa** [comment] 2022-07-04 11:02
Yeah let's close it. If you hit the same issue again, please feel free to reopen it.

Thank you for your patience on all this too!

**Closed by heitorlessa** 2022-07-04 11:02 UTC
Labels: area/lambda-layers

**Comment by macdrorepo** [comment] 2022-07-04 11:50
Can confirm my custom layer is working, AWS lately is mehhh.
Thx to all for reaching out!
