### ISSUE TITLE
Bug: S3Model not compatible with ObjectRemoved events

### ISSUE THREAD

**Issue by barreeeiroo** [awslabs/aws-lambda-powertools-python#1637] opened 2022-10-23 15:50 UTC
### Expected Behaviour

After deleting an object from S3, if a Lambda catches this event, they should be able to parse it. This event name from S3 is `ObjectDeleted:*`.

### Current Behaviour

A `ValidationError` is thrown because of the missing `size` and `eTag` attributes.

```
Records -> 0 -> s3 -> object -> size
  field required (type=value_error.missing)
Records -> 0 -> s3 -> object -> eTag
  field required (type=value_error.missing)
```

The `ObjectDeleted` event does not include those attributes.

### Code snippet

```python
parse(model=S3Model, event=json.loads(s3_message))
```

Payload Example: https://github.com/awslabs/aws-lambda-powertools-python/issues/1637#issuecomment-1288170059

### Possible Solution

Update `S3Object` so that both `size` and `eTag` are optional:

```python
class S3Object(BaseModel):
    key: str
    size: Optional[NonNegativeFloat]
    eTag: Optional[str]
    sequencer: str
    versionId: Optional[str]
```

### Steps to Reproduce

1. Create a Lambda function and an S3 bucket
2. Trigger the Lambda function through S3 events, and enable the `ObjectDeleted` type
3. Delete an object from S3
4. `S3Model` will raise a `ValidationError`

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.8

### Packaging format used

PyPi

**Comment by heitorlessa** [comment] 2022-10-23 17:48
@barreeeiroo thank you for flagging this - would you be able to send a quick fix PR marking them as Optional, please?

We're launching V2 tomorrow morning and we could include the fix in.

Otherwise we can make a V1 patch release afterwards.

Thank you!!

**Comment by barreeeiroo** [comment] 2022-10-23 18:07
@heitorlessa done, the PR should be available now: [PR#1638](https://github.com/awslabs/aws-lambda-powertools-python/pull/1638). I couldn't really test the change right now, but if strictly needed I can fully test it tomorrow.

**Comment by heitorlessa** [comment] 2022-10-23 18:11
> @heitorlessa done, the PR should be available now: [PR#1638](https://github.com/awslabs/aws-lambda-powertools-python/pull/1638). I couldn't really test the change right now, but if strictly needed I can fully test it tomorrow.

Thank you!! Do you happen to have a copy of the delete event?

If you do, please add to the issue. We can complete the tests before releasing it tomorrow (~10am Amsterdam time)

**Comment by barreeeiroo** [comment] 2022-10-23 18:22
Sure, here it is:

```json
{
  "eventVersion": "2.1",
  "eventSource": "aws:s3",
  "awsRegion": "us-west-2",
  "eventTime": "2022-10-23T15:37:51.707Z",
  "eventName": "ObjectRemoved:Delete",
  "userIdentity": {
    "principalId": "[REDACTED]"
  },
  "requestParameters": {
    "sourceIPAddress": "[REDACTED]"
  },
  "responseElements": {
    "x-amz-request-id": "[REDACTED]",
    "x-amz-id-2": "[REDACTED]"
  },
  "s3": {
    "s3SchemaVersion": "1.0",
    "configurationId": "[REDACTED]",
    "bucket": {
      "name": "[REDACTED]",
      "ownerIdentity": {
        "principalId": "[REDACTED]"
      },
      "arn": "[REDACTED]"
    },
    "object": {
      "key": "[REDACTED]",
      "sequencer": "[REDACTED]"
    }
  }
}
```

Seems like the rest of the payload is correct.

**Comment by ran-isenberg** [comment] 2022-10-23 18:44
Thanks @barreeeiroo  for finding and solving this!

@heitorlessa  maybe we can add a validator that checks that they are indeed optional only if the event name is ObjectRemoved:Delete?  For other S3object events, these fields are not optional, right?

**Comment by ran-isenberg** [comment] 2022-10-23 18:52
@heitorlessa  i think it's also a bug for the S3Object dataclass.

**Comment by barreeeiroo** [comment] 2022-10-23 18:57
No problem @ran-isenberg! I also thought about adding a conditional validator like this:

```python
class S3Object(BaseModel):
    key: str
    size: Optional[NonNegativeFloat] # This needs to still be defined as Optional
    eTag: Optional[str] # This needs to still be defined as Optional
    sequencer: str
    versionId: Optional[str]

class S3RecordModel(BaseModel):
    eventVersion: str
    eventSource: Literal["aws:s3"]
    awsRegion: str
    eventTime: datetime
    eventName: str
    userIdentity: S3Identity
    requestParameters: S3RequestParameters
    responseElements: S3ResponseElements
    s3: S3Message
    glacierEventData: Optional[S3EventRecordGlacierEventData]

    @root_validator
    def validate_s3_object(cls, values):
        event_name = values.get('eventName')
        s3_object = values.get('s3').get('object')
        if 'ObjectRemoved' not in event_name:
            if not s3_object.get('size') or not s3_object.get('eTag'):
                raise ValueError('S3Object.size and S3Object.eTag are required for non-ObjectRemoved events')
        return values
```

But wasn't really sure about it as I couldn't find any AWS official documentation stating which attributes are required for each event type. Is there any document which lists all the attributes provided for each event type from S3?

**Comment by heitorlessa** [comment] 2022-10-23 18:58
For now, let’s make them optional - it’s a two-way door (we can always add
the validators back as it’s a non-breaking change).

We need a better strategy for Parser. It’s starting to break customers more
frequently.

Maybe a rule for now could be to only add any additional Parser Models
until we have either E2E or regular runs on its various configurations —
e.g., MSK takes 30m to setup which isn’t suitable for 30m as it adds up
quickly.

@Ran - if you’ve got ideas on how we can make Parser more accurate, despite
not having official schemas from Lambda (actual root cause), could you kick
off a RFC on this, please?

Thanks a lot you both, truly.

**Comment by ran-isenberg** [comment] 2022-10-23 19:00
@heitorlessa  it's not just the parser in this case, also regular data classes are broken too.

**Comment by ran-isenberg** [comment] 2022-10-23 19:00
> No problem @ran-isenberg! I also thought about adding a conditional validator like this:
> 
> ```python
> class S3Object(BaseModel):
>     key: str
>     size: Optional[NonNegativeFloat] # This needs to still be defined as Optional
>     eTag: Optional[str] # This needs to still be defined as Optional
>     sequencer: str
>     versionId: Optional[str]
> 
> class S3RecordModel(BaseModel):
>     eventVersion: str
>     eventSource: Literal["aws:s3"]
>     awsRegion: str
>     eventTime: datetime
>     eventName: str
>     userIdentity: S3Identity
>     requestParameters: S3RequestParameters
>     responseElements: S3ResponseElements
>     s3: S3Message
>     glacierEventData: Optional[S3EventRecordGlacierEventData]
> 
>     @root_validator
>     def validate_s3_object(cls, values):
>         event_name = values.get('eventName')
>         s3_object = values.get('s3').get('object')
>         if 'ObjectRemoved' not in event_name:
>             if not s3_object.get('size') or not s3_object.get('eTag'):
>                 raise ValueError('S3Object.size and S3Object.eTag are required for non-ObjectRemoved events')
>         return values
> ```
> 
> But wasn't really sure about it as I couldn't find any AWS official documentation stating which attributes are required for each event type. Is there any document which lists all the attributes provided for each event type from S3?

I didnt find any official docs, otherwise i'd have the even name as a literal of closed event types list :(

**Comment by heitorlessa** [comment] 2022-10-23 19:02
Yes, both. The difference is that Parser breaks at runtime, while data
classes varies on how the property is retrieved (some has sentinel values).

**Comment by ran-isenberg** [comment] 2022-10-23 19:02
@barreeeiroo yeah that makes sense! nice one.
I'll open a PR with tests in a few min.

**Comment by heitorlessa** [comment] 2022-10-23 19:06
> > No problem @ran-isenberg! I also thought about adding a conditional validator like this:
> 
> > 
> 
> > ```python
> 
> > class S3Object(BaseModel):
> 
> >     key: str
> 
> >     size: Optional[NonNegativeFloat] # This needs to still be defined as Optional
> 
> >     eTag: Optional[str] # This needs to still be defined as Optional
> 
> >     sequencer: str
> 
> >     versionId: Optional[str]
> 
> > 
> 
> > class S3RecordModel(BaseModel):
> 
> >     eventVersion: str
> 
> >     eventSource: Literal["aws:s3"]
> 
> >     awsRegion: str
> 
> >     eventTime: datetime
> 
> >     eventName: str
> 
> >     userIdentity: S3Identity
> 
> >     requestParameters: S3RequestParameters
> 
> >     responseElements: S3ResponseElements
> 
> >     s3: S3Message
> 
> >     glacierEventData: Optional[S3EventRecordGlacierEventData]
> 
> > 
> 
> >     @root_validator
> 
> >     def validate_s3_object(cls, values):
> 
> >         event_name = values.get('eventName')
> 
> >         s3_object = values.get('s3').get('object')
> 
> >         if 'ObjectRemoved' not in event_name:
> 
> >             if not s3_object.get('size') or not s3_object.get('eTag'):
> 
> >                 raise ValueError('S3Object.size and S3Object.eTag are required for non-ObjectRemoved events')
> 
> >         return values
> 
> > ```
> 
> > 
> 
> > But wasn't really sure about it as I couldn't find any AWS official documentation stating which attributes are required for each event type. Is there any document which lists all the attributes provided for each event type from S3?
> 
> 
> 
> I didnt find any official docs, otherwise i'd have the even name as a literal of closed event types list :(

+1. It's what I shared earlier - the root cause is not having an event schema. We derived based on events we trigger - our models can only be as good as our tests and "contracts" being respected by their original producers.

So far we've noticed a few variations that end up making one or more properties to be either omitted or have different casing:

- Event Source default settings 

- Event Source custom settings (FIFO, different action like Deleted here)

- Event Source connected with another event source (SNS->SQS->Lambda is slightly different than SNS->Lambda)

**Comment by ran-isenberg** [comment] 2022-10-23 19:07
@heitorlessa  I'm getting an error on my dev env - 
"tests/e2e/utils/lambda_layer/powertools_layer.py:6: in <module>
    from checksumdir import dirhash
E   ModuleNotFoundError: No module named 'checksumdir'


I ran make dev but it didnt install it

**Comment by ran-isenberg** [comment] 2022-10-23 19:08
after installing it manually it now says:
"E   ImportError: cannot import name 'aws_apigatewayv2_alpha' from 'aws_cdk' (/Users/ranisenberg/Programming/aws-lambda-powertools-python/.venv/lib/python3.9/site-packages/aws_cdk/__init__.py)"

**Comment by heitorlessa** [comment] 2022-10-23 19:47
Sorry it’s Sunday, so we’ll look into tomorrow after V2 launch. I’m not
comfortable with the validators - I can’t be confident this won’t break in
another unexpected way.

Diego had a PR but it’s missing test. Let’s be mindful and foster
first-time contributors, please.

I’ll wake up earlier as we’ve had too many last minute papercuts for the
launch last Friday - we’ve got to launch tomorrow morning the earliest and
need to reduce deltas.

Thanks everyone for the patience and more so for messaging this late on a
Sunday.

Have a great rest and we crack on tomorrow after launch

**Comment by ran-isenberg** [comment] 2022-10-23 19:51
@heitorlessa  of course. It's 11PM here, didnt expect you to merge it :)
I didnt know how to add Diego's PR to mine, but you can merge his code and then mine so his commit is added.

The validator does not break older tests and it's very specific to the delete event.

**Comment by barreeeiroo** [comment] 2022-10-23 20:29
For reference, providing this link to this AWS page: https://docs.aws.amazon.com/filegateway/latest/files3/refresh-cache.html
It shows an example payload in Step 15 for `ObjectRemoved` where they show the `object` having only `eTag` and `key` attributes.

**Comment by heitorlessa** [comment] 2022-10-24 06:24
Releasing v2.0.0a4 pre-release: https://github.com/awslabs/aws-lambda-powertools-python/actions/runs/3310473745

We should make the official launch at 10am CET (Amsterdam time)

**Comment by heitorlessa** [comment] 2022-10-24 11:05
Released in V2 now: https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v2.0.0

**Closed as completed by heitorlessa** 2022-10-24 11:05 UTC
Labels: bug
