### ISSUE TITLE
Bug: Python 3.10 :: SQSEvent :: AttributeError: 'dict' object has no attribute 'records'

### ISSUE THREAD

**Issue by CloutKhan** [awslabs/aws-lambda-powertools-python#4919] opened 2024-08-09 00:56 UTC
### Expected Behaviour

`events.records` can be used as the iterator over records.

### Current Behaviour

AttributeError: 'dict' object has no attribute 'records'

### Code snippet

```python
from aws_lambda_powertools.utilities.data_classes.sqs_event import SQSEvent
from aws_lambda_powertools.utilities.typing import LambdaContext

def lambda_handler(sqs_event: SQSEvent, context: LambdaContext):
    for record in event.records: # where event["Records"] does not fail.
        pass
```

### Steps to Reproduce

Try to access `event.records` as a property on an `SQSEvent` instance.

### Powertools for AWS Lambda (Python) version

2.42.0

### AWS Lambda function runtime

3.10

### Packaging format used

Lambda Layers

**Comment by leandrodamascena** [comment] 2024-08-09 13:04
Hi @CloutKhan! Thanks for opening this issue. This is actually not a bug, what is happening here is because you are using `SQSEvent` in your function signature but you are not using the `@event_source` decorator, so we are not able to convert your dict to an object. Check if this works with the code below:

```python
from aws_lambda_powertools.utilities.data_classes import event_source, SQSEvent
from aws_lambda_powertools.utilities.typing import LambdaContext

@event_source(data_class=SQSEvent)
def lambda_handler(event: SQSEvent, context: LambdaContext):
    for record in event.records: # where event["Records"] does not fail.
        pass
```

thanks

**Comment by leandrodamascena** [comment] 2024-08-11 21:52
Please reopen this issue if you need any further support @CloutKhan!

Closing as not a bug.

**Closed as completed by leandrodamascena** 2024-08-11 21:52 UTC
Labels: not-a-bug, event_sources
