### ISSUE TITLE
feat:(parser): Add KinesisFirehoseEvent

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#1071] opened 2022-03-08 13:17 UTC
Similar to what https://github.com/awslabs/aws-lambda-powertools-python/issues/1059 mentions

Add support for a KinesisFirehoseEvent parser model and envelope for request and response.

**Comment by gwlester** [comment] 2022-04-21 04:44
This appears to be a duplicate of [feat(data-classes): Add KinesisFirehoseEvent #1059](https://github.com/awslabs/aws-lambda-powertools-python/issues/1059).  Since the other issue has details, I'd suggest this issue be closed/rejected.

**Comment by ran-isenberg** [comment] 2022-04-21 04:46
@gwlester Parser and data classes are two completely different utilities and implementations.

**Comment by gwlester** [comment] 2022-04-21 04:50
@ran-isenberg -- sorry you are correct.  Too late at night!  I did not see the what inside of feat!!!

Should I delete this and the other comment??

**Comment by ran-isenberg** [comment] 2022-04-21 04:50
no worries, dont delete

**Comment by michaelbrewer** [comment] 2022-04-21 06:57
yep, we made things nice and confusing :)

**Comment by heitorlessa** [comment] 2022-10-24 11:08
released

**Closed by heitorlessa** 2022-10-24 11:08 UTC
Labels: feature-request, area/parser
