### ISSUE TITLE
Static typing: typing error when using tracer alongside parser

### ISSUE THREAD

**Issue by LouisAmon** [awslabs/aws-lambda-powertools-python#1989] opened 2023-03-08 15:47 UTC
### Static type checker used

mypy (project's standard)

### AWS Lambda Powertools for Python version

2.9.0

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

### Static type checker info

When you use the powertools `tracer` decorator alongside the `event_parser` decorator, the typing gets confused and throws an error on the `tracer` about the event not being of the correct type.

It's a typing error : the code is otherwise functional so my solution so far is to `# type: ignore`, but I felt I should report it here

<img width="946" alt="image" src="https://user-images.githubusercontent.com/6024791/223752306-afb81d0b-12f3-43e1-a7d4-ca1564bf6147.png">

### Code snippet

```python
from aws_lambda_powertools import Tracer
from aws_lambda_powertools.utilities.typing import LambdaContext
from aws_lambda_powertools.utilities.parser import event_parser, BaseModel

tracer = Tracer()


class PaymentEvent(BaseModel):
    charge_id: str


def collect_payment(charge_id: str) -> str:
    return f"dummy payment collected for charge: {charge_id}"


@tracer.capture_lambda_handler
@event_parser(model=PaymentEvent)
def handler(event: PaymentEvent, context: LambdaContext) -> str:
    return collect_payment(charge_id=event.charge_id)
```

### Steps to Reproduce

Just paste the code snippet in a VSCode IDE with Pyright or mypy enabled
(Mypy returns a different error, but it returns one nonetheless if you enable `--strict` : "Untyped decorator makes function "handler" untyped")

**Comment by heitorlessa** [comment] 2023-03-08 16:03
Thank you for reporting @LouisAmon - I took liberty to correct the issue description to reflect this is a static typing issue and [not a bug](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/MAINTAINERS.md#is-that-a-bug).

[Strict typing is in our roadmap](https://awslabs.github.io/aws-lambda-powertools-python/2.9.1/roadmap/#strict-typing). Adding this to our backlog, PRs welcomed.

**Comment by leandrodamascena** [comment] 2023-09-01 23:12
We understand the demand of our customers to have a project with strict typing, which will come in new major versions of Powertools. We don't know yet if it's V3 or V4, as we need to validate all the changes we need to make, which may include breaking changes.

We are prioritizing other backlog items such as observability provider, data masking, Redis for idempotency, and OpenAPI, among others.

I'm going to close this issue but if you want to submit a PR, we can reopen this issue and work to have the PR merged.

Thanks.

**Closed as completed by leandrodamascena** 2023-09-01 23:12 UTC
Labels: help wanted, typing, not-a-bug

**Comment by ambasta** [comment] 2024-01-05 08:51
I think this issue persists still

```
Parameter 1: type "Dict[Unknown, Unknown]" cannot be assigned to type "PaymentEvent" 
```
