### ISSUE TITLE
Validation-Inconsistency on REST-API

### ISSUE THREAD

**Issue by dschro-1993** [awslabs/aws-lambda-powertools-python#4125] opened 2024-04-12 14:12 UTC
### Expected Behaviour

Hey Guys, when I create a BaseModel like this

```
class Foo(BaseModel):
  AccountId: str = Field(pattern=r"^\d{12}$")
```

And create an Instance of it like this:
```
foo = Foo(AccountId="12345678901a")
```

you will see the following exception:
```
...should match pattern '^\d{12}$' [type=pattern_mismatch, input_value='12345678901a', input_type=str]
```

If I let the APIGatewayRestResolver do the validation implicitly:
```
api = event_handler.APIGatewayRestResolver(
  enable_validation = True
)
```

And pass a payload to the endpoint like:
```
{"AccountId": "12345678901a"}
```

it is accepted/valid...do you know why that is?
When `min_length` and `max_length` is used for validation only, I see the expected behaviour...
But `pattern` seems to be skipped/iqnored when validation is done implicitly.
Any help is appreciated.

### Current Behaviour

APIGatewayRestResolver should return same Exception and 422 when payload does not match pattern.

### Code snippet

see above

### Steps to Reproduce

see above

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.12

**Comment by rubenfonseca** [comment] 2024-04-12 14:15
Hi @dschro-1993 can you show me your api handler code that uses `Foo`?

**Comment by dschro-1993** [comment] 2024-04-12 14:40
Handler:
```
from aws_lambda_powertools import event_handler

# ...router-imports...

api = event_handler.APIGatewayRestResolver(
  enable_validation = True
)

api.include_router(...)

def entrypoint(request: dict, context: dict) -> dict:
  return api.resolve(
    request,
    context,
  )
```

Router:
```
from aws_lambda_powertools.event_handler.api_gateway import Router

from models import Foo

router = Router()

@router.post("/foo")
def create(foo: Foo) -> dict:
  """Foo Create-Request"""
  # ...
```

Model:
```
class Foo(BaseModel):
  AccountId: str = Field(pattern=r"^\d{12}$")
```

**Comment by rubenfonseca** [comment] 2024-04-12 17:12
**Can you please tell me which Pydantic version are you using?**

I've just deployed this code for a test:

```python
from aws_lambda_powertools import Logger
from aws_lambda_powertools.event_handler import (
    APIGatewayRestResolver,
)
from aws_lambda_powertools.event_handler.api_gateway import Router
from pydantic import Field, BaseModel

logger = Logger()


class Foo(BaseModel):
    AccountId: str = Field(pattern=r"^\d{12}$")


router = Router()


@router.post(
    "/foo",
)
def helloworld(foo: Foo) -> dict:
    logger.info("Hello, World!", foo=foo)
    return {"accountId": foo.AccountId}


app = APIGatewayRestResolver(enable_validation=True)
app.include_router(router)


@logger.inject_lambda_context
def lambda_handler(event, context):
    return app.resolve(event, context)
```

A request with a wrong body failed:
<img width="976" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/10713/5103f2e1-3c00-4d3b-8f43-6a968dca733e">

But a request with a good body succeeded:
<img width="865" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/10713/2776d160-f9ec-4d2f-9d23-7d953e6af125">

**Comment by dschro-1993** [comment] 2024-04-12 17:17
I use the Powertools lambda layer arm64 in its latest version:
https://docs.powertools.aws.dev/lambda/python/latest/#lambda-layer
```
# ...
resource "aws_lambda_function" "foo" {
  #...
  layers = [
    "arn:aws:lambda:${data.aws_region.current.name}:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:68"
  ]
}
```

**Comment by dschro-1993** [comment] 2024-04-12 17:21
Oh damn, that layer is built upon Pydantic v1, correct? So I would have to bundle v2 on my own if I want to see v2 behaviour in my lambda?

**Comment by rubenfonseca** [comment] 2024-04-12 17:33
Let me try locally with v1 first to understand if this is the cause of problem

**Comment by rubenfonseca** [comment] 2024-04-12 17:39
Got it, with Pydantic v1 you have to use `regex` instead of `pattern`! Just tested it and it works :D

<img width="860" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/10713/b3c06a90-a377-4fe4-ba31-6dfb9e67676e">

We have [an issue collecting interest](https://github.com/aws-powertools/powertools-lambda-python/issues/2939) for a managed Layer that includes Pydantic v2. Can you add your +1 there?

If this solves your problem, let me know if we can close this issue :)

**Comment by dschro-1993** [comment] 2024-04-12 18:30
Thanks for your investigation, that was very helpful!
Left a +1 for the v2 layer :)

**Comment by rubenfonseca** [comment] 2024-04-12 18:39
Awesome! Thank you for opening this report :) Closing it for now

**Closed as completed by rubenfonseca** 2024-04-12 18:39 UTC
Labels: bug, layers
