### ISSUE TITLE
Bug: v2.40.0 undocumented breaking change in Router

### ISSUE THREAD

**Issue by ghost** [awslabs/aws-lambda-powertools-python#4650] opened 2024-06-28 09:40 UTC
### Expected Behaviour

In out code we accessed `current_event` directly from `Router` class befor 2.40.0

### Current Behaviour

In 2.40.0 version `current_event` available in `AppSyncResolver` only

### Code snippet

```python
from aws_lambda_powertools.event_handler import AppSyncResolver
from aws_lambda_powertools.event_handler.appsync import Router

user_router = Router()

@user_router.resolver(field_name="user")
def get_user() -> dict:
    return service.get_user_by_id(user_id=user_router.current_event.identity.sub)

app = AppSyncResolver()
app.include_router(user_router)
```

### Steps to Reproduce

call `current_event` attribute from Router class

### Powertools for AWS Lambda (Python) version

2.40.0

### AWS Lambda function runtime

3.12

### Packaging format used

Lambda Layers

**Comment by leandrodamascena** [comment] 2024-06-28 09:49
Checking now.

**Comment by leandrodamascena** [comment] 2024-06-28 10:31
Hi @karvetskiy, thanks for opening this issue and reporting this bug. Our tests didn't catch accessing `current_event` using the `Router` object directly and because of this we have this breaking change in this release, sorry about that. I'm working to fix and will release a new version in a few minutes.

Thanks

**Comment by leandrodamascena** [comment] 2024-06-28 10:46
Hey @karvetskiy! If I publish a pre-release on Pypi, can you test if the issue is resolved in your environment before we release a new patch release? Thanks

**Comment by ghost** [comment] 2024-06-28 11:03
Hey @leandrodamascena! Just checked alpha version, still can't access `current_event`. 
Looks like new `Router` class in `event_handler.graphql_appsync.router` inhered from wrong implementation of `BaseRouter` class.
It has different implementation in v2.39.1 (see [code](https://github.com/aws-powertools/powertools-lambda-python/blob/v2.39.1/aws_lambda_powertools/event_handler/appsync.py#L12))

**Comment by heitorlessa** [comment] 2024-06-28 11:04
he hasn't published yet, will ping you shortly @karvetskiy

**Comment by heitorlessa** [comment] 2024-06-28 11:15
PR incoming, we've been wrestling with static typing and additional tests to be quadruple sure this would work on areas we were missing tests too.

Once we merge and publish the alpha release we ping you

**Comment by heitorlessa** [comment] 2024-06-28 11:26
kicked off pre-release (should be in PyPi in ~6 minutes or so).. https://github.com/aws-powertools/powertools-lambda-python/actions/runs/9712027684

**Comment by leandrodamascena** [comment] 2024-06-28 11:33
Hey @karvetskiy! alpha release is available. Can you test pls?

https://pypi.org/project/aws-lambda-powertools/2.40.1a1/

**Closed as completed** 2024-06-28 12:25 UTC
Labels: bug, event_handlers
