### ISSUE TITLE
Bug: ConditionsValidator cannot handle validate action

### ISSUE THREAD

**Issue by UrielAbergel** [awslabs/aws-lambda-powertools-python#1870] opened 2023-01-29 12:03 UTC
### Expected Behaviour

when entering aws_lambda_powertools/utilities/feature_flags/schema.py/validate_condition_action:254 the action RuleAction.IN should be in the RuleAction.__member__

### Current Behaviour

RuleAction.IN raises an exception because it is an enum and cannot be attached to strings in the array.

### Code snippet

```python
main():
   ServiceConfig(service_name='configuration',configuration_name='configuration',configuration={'features': {'': {'boolean_type': True, 'default': False, 'rules': {'Rule by tenant ID': {'when_match': True, 'conditions': [{'action': <RuleAction.IN: 'IN'>, 'key': 'ti', 'value': [''ts']}]}}}, 'pl': {'boolean_type': False, 'default': 100, 'rules': {}}, 'pr': {'boolean_type': True, 'default': True, 'rules': {}}}}
```

### Possible Solution

to take the logic from version 2.6.0 or to take the action.value and check if its in the array

### Steps to Reproduce

update your version to 2.7.0 and then run ServiceConfig object with the new configuration that have RuleAction.IN in the rule dict then debug until you go to aws_lambda_powertools/utilities/feature_flags/schema.py/validate_condition_action:254 and then see the failure

### AWS Lambda Powertools for Python version

2.7.0

### AWS Lambda function runtime

3.6

### Packaging format used

Serverless Application Repository (SAR) App

**Comment by leandrodamascena** [comment] 2023-01-29 12:43
Hi @UrielAbergel, how are you? Thank you for opening this issue for us to investigate a possible bug. I need to understand a few things to start an investigation.

- This `ServiceConfig` function is part of your application, correct? From what I understand this seems to configure a rule in AppConfig.
- You also say that to be able to reproduce it, we must install version 2.7.0 and debug until we reach line 254 of the `schema.py` file, which has the `valid_condition_action` function. But in version 2.7.0, this [valid_condition_action](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/feature_flags/schema.py#L295) function is on line 295 and not on line 254 anymore as we added code for the TimeBased feature.
- I looked again at the PR (https://github.com/awslabs/aws-lambda-powertools-python/pull/1846/files) that we merged  and we didn't change that logic.
- And I simulated this feature here with the new 2.7.0 code and it worked fine.

![image](https://user-images.githubusercontent.com/4295173/215326622-30dc0ba7-317d-4eef-b39c-672e74f66750.png)
![image](https://user-images.githubusercontent.com/4295173/215326750-638fd659-5e3a-4012-9fc2-93c7edde0787.png)
![image](https://user-images.githubusercontent.com/4295173/215326834-19704a17-ee6c-4142-8e4e-04bb810597b5.png)

Please let me know if I'm missing something, but it seems to be working fine.

**Comment by UrielAbergel** [comment] 2023-01-29 12:54
It looks like this bug is from the old version then 2.7.0 will checkout and see if the bug reproduced in my current version

**Closed as completed** 2023-01-29 12:53 UTC
Labels: bug, need-more-information, cant-reproduce
