### ISSUE TITLE
Bug: Logs populating into cloudwatch as multiple lines instead of a single object

### ISSUE THREAD

**Issue by thault** [awslabs/aws-lambda-powertools-python#3763] opened 2024-02-13 19:20 UTC
### Expected Behaviour

I'm expecting the logs to populate as a single json object in cloudwatch.

![expected](https://github.com/aws-powertools/powertools-lambda-python/assets/526570/ee580a14-5fba-4afc-a283-ee3f579aa2f1)

### Current Behaviour

Logger logs are shown as single lines within cloudwatch creating a lot of lines within the log stream. I have tried the log format as text and JSON and get the issue both ways. 

![actual](https://github.com/aws-powertools/powertools-lambda-python/assets/526570/bf251e70-045a-4603-9108-510375066b8f)

### Code snippet

```python
from aws_lambda_powertools import Logger
from aws_lambda_powertools.utilities.typing import LambdaContext
logger = Logger(log_uncaught_exceptions=True)

@logger.inject_lambda_context(log_event=True)
def lambda_handler(event, context)
    logger.info("Token retrieval started")
```

### Steps to Reproduce

Lambda using the powertools layer arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV2:60, followed the guide for basic logging with context included. All logs created via logger.info() or logger.debug() have the issue.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.12

### Packaging format used

Lambda Layers

**Comment by heitorlessa** [comment] 2024-02-14 09:23
trying to reproduce it now... from my recollection that only happens when you have `\n` since CloudWatch Logs creates a new line like that. `Logger` prints as a string. The only behavior change is when you have [`POWERTOOLS_DEV`](https://docs.powertools.aws.dev/lambda/python/latest/#optimizing-for-non-production-environments) env var where [we increase indentation ](https://github.com/aws-powertools/powertools-lambda-python/blob/f4f9021618ad66fd50bfb8be4bb3fe70b8ba62c3/aws_lambda_powertools/logging/formatter.py#L128).

**Comment by heitorlessa** [comment] 2024-02-14 09:40
Couldn't reproduce, will try more scenarios

* [x] Same code snippet on Python 3.11
* [x] Same code snippet older Powertools for AWS Lambda version (2.31.0)
* [x] Same code snippet on Python 3.12
* [x] Use `POWERTOOLS_DEV` env
* [x] Use `POWERTOOLS_DEBUG` env
* [x] Copy [existing Logger config](https://docs.powertools.aws.dev/lambda/python/latest/core/logger/#how-can-i-enable-powertools-for-aws-lambda-python-logging-for-imported-libraries) to other std/libraries (noticed in your screenshot X-Ray/boto appears)

<img width="1594" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/a5984404-fcb0-447a-979c-fbabea7f9baa">

**Comment by heitorlessa** [comment] 2024-02-14 09:55
As expected, reproduced with `POWERTOOLS_DEV` where indentation is increased for local debugging. Checking the last scenario to triple check.

**Local effect (intended use case)**

<img width="1565" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/88754801-d103-4141-9bc3-c4f1f35eac73">

**Local effect with SAM CLI `logs` pulling from CloudWatch Logs**

<img width="1555" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/452ac7fb-678a-466c-8491-c55a4a7b46f9">

**CloudWatch Logs effect (extra indentation is transformed**

<img width="1393" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/09b23b17-7da4-4c14-a558-62adc369c0ea">

**Comment by heitorlessa** [comment] 2024-02-14 10:07
All scenarios tested, this only seems to occur due to `POWERTOOLS_DEV` as expected -- could you please check whether you have that turned on?

---

**Logger config copied to boto3+X-Ray SDK loggers + DEBUG log level**

<img width="1407" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/9de26773-d6d6-408b-84f4-fda8bf44b7a2">

**Comment by thault** [comment] 2024-02-14 14:06
Looks like you are correct that it's from the POWERTOOLS_DEV; when I set that to false the logs started populating as single lines. 

So this is expected behavior when POWERTOOLS_DEV is true; is there a way to work around that? It makes sense when running locally with SAM, but it makes the logs a pain when testing in AWS.

**Comment by heitorlessa** [comment] 2024-02-14 14:08
I'm sure we can figure something out -- what made you enable `POWERTOOLS_DEV`? That will help understand alternative solutions or trade-offs we might be able to make.

Customers also use this feature with `pytest` live debugging feature.

**Comment by heitorlessa** [comment] 2024-02-14 16:30
Summarizing our [discussion on Discord](https://discord.com/channels/1006478942305263677/1006527338621710376/1207052615968493638).

What you were after was `POWERTOOLS_DEBUG` to get extra details about every operation (Logger) while using CloudWatch Logs view.

`POWERTOOLS_DEV` on the other hand is focused on local development, where you want to run your code locally with tools like SAM CLI, or `pytest` live log feature.

I'm closing this issue and [created a PR](https://github.com/aws-powertools/powertools-lambda-python/pull/3770) to make this more explicit in our docs to prevent future confusion.

Thank you so much for taking the time to report this and help improve the docs!

**Closed as completed by heitorlessa** 2024-02-14 16:30 UTC
Labels: not-a-bug
