### ISSUE TITLE
IntelliSense for app.current_event defaults to BaseProxyEvent rather than APIGatewayProxyEvent

### ISSUE THREAD

**Issue by bb-rrogers** [awslabs/aws-lambda-powertools-python#882] opened 2021-12-10 01:58 UTC
When attempting to lookup path_parameters from the app.current_event.path_parameters PyCharm indicates it cannot identify this property. Looking at the type of object returned from app.current_event it appears it uses BaseProxyEvent rather than the APIGatewayProxyEvent.

## Expected Behavior
`app.current_event.path_parameters` provides intellisense for the property.

## Current Behavior
`app.current_event.path_parameters` does not provide intellisense for the property.

## Steps to Reproduce (for bugs)
Simply looking up the object of app.current_event shows it's a BaseProxyEvent and so the intellsense is only for the default. We have to type hint that it's a APIGatewayProxyEvent to avoid IDE errors.

## Environment

* **Powertools version used**: 1.22.0
* **Packaging format (Layers, PyPi)**: Layers
* **AWS Lambda function runtime:** Python 3.9

**Comment by michaelbrewer** [comment] 2021-12-10 04:15
@bb-rrogers - this would be a duplicate of https://github.com/awslabs/aws-lambda-powertools-python/issues/761

**Comment by heitorlessa** [comment] 2021-12-10 07:33
hey @bb-rrogers closing as a duplicate as @michaelbrewer pointed out. We need to refactor the current implementation and use [overload functions](https://mypy.readthedocs.io/en/stable/more_types.html#function-overloading) to ensure you get the right type of event depending on the ProxyEvent you choose.

**Closed by heitorlessa** 2021-12-10 07:33 UTC
Labels: bug, triage
