### ISSUE TITLE
Tracer reports caught exceptions

### ISSUE THREAD

**Issue by latacora-tomekr** [awslabs/aws-lambda-powertools-python#334] opened 2021-03-12 17:56 UTC
👋 It looks like powertools will report an exception to X-Ray even if the exception is caught and handled. The use case we're seeing is with calling Secrets Manager. Here we make the following call:

**What were you trying to accomplish?**

```python
def get_secrets(secret_name) -> dict:
    try:
        get_secret_value_response = client.get_secret_value(SecretId=secret_name)
    except ClientError as e:
        if e.response["Error"]["Code"] == "ResourceNotFoundException":
            if "AWSCURRENT" in e.response["Message"]:
                logger.warning(f"{secret_name} exists but is empty.")
            else:
                logger.warning(
                    f"The requested secret {secret_name} was not found. Create the secret first."
                )
            return {}
        else:
            raise RuntimeError("Couldn't retrieve secrets")
    else:
        return json.loads(get_secret_value_response["SecretString"])
```

In this case where the secret exists but is empty is totally fine here and although boto3 technically throws an exception, we catch it here and continue processing. However I think powertools is hooking into boto3, seeing the exception, and reporting it as an Error in X-Ray. I'd like exception auto-capture anywhere else but in this case I wouldn't want powertools reporting it as an error. Is there a way to handle this?

## Expected Behavior

Would except handled exceptions to not report an error to X-Ray.

## Current Behavior

Powertools reports an error.

## Possible Solution

Annotate/configure `client.get_secret_value` to not report exceptions from boto3.

## Steps to Reproduce (for bugs)
See code above

## Environment

* **Powertools version used**: v1.11.0
* **Packaging format (Layers, PyPi)**: PyPi
* **AWS Lambda function runtime:** Python 3.6
* **Debugging logs**

```python
2021-03-12 17:54:02,435 aws_lambda_powertools.tracing.tracer [DEBUG] Verifying whether Tracing has been disabled
2021-03-12 17:54:02,791 aws_lambda_powertools.tracing.tracer [DEBUG] Annotating cold start
2021-03-12 17:54:02,791 aws_lambda_powertools.tracing.tracer [DEBUG] Calling lambda handler
2021-03-12 17:54:12,673 aws_lambda_powertools.tracing.tracer [DEBUG] Received lambda handler response successfully
```

**Comment by heitorlessa** [comment] 2021-03-12 18:10
hey @latacora-tomekr, thanks for raising it! 

At first glance it looks like AWS X-Ray SDK is identifying an exception as part of the call chain and adding it regardless whether it's handled or not: https://github.com/aws/aws-xray-sdk-python/blob/508f929fee495710656c0c1478f8873a2e9e5666/aws_xray_sdk/core/models/subsegment.py#L70

 Tracer `capture_method` is simply a thin wrapper with super powers for `xray_recorder.in_subsegment` which uses this ^ context manager. 

 I'll try taking a look at it next week, but you safely open up an issue upstream with X-Ray SDK (we can do it too!). 

Thanks and have a great weekend

**Comment by latacora-tomekr** [comment] 2021-03-12 20:43
@heitorlessa thanks for the quick response! Filed an issue upstream https://github.com/aws/aws-xray-sdk-python/issues/274

**Comment by heitorlessa** [comment] 2021-03-17 16:47
hey @latacora-tomekr, could you share a complete snippet of what's failing on you? 

I couldn't replicate it. I also tried step through debugging to see whether X-Ray SDK code was correctly receiving `None` when an exception was handled - That is, `__exit__(exc...)` should be None when handled correctly. 

As expected, the context manager arguments only get populated if an exception wasn't handled and `__exit__` was triggered to clean up.

I'm using Python 3.8 and used this to try replicating it: https://github.com/heitorlessa/pt_issue274/blob/master/hello_world/app.py

Deployed URL to trigger a conditional failure: https://ipsucx5c15.execute-api.eu-west-1.amazonaws.com/Prod/hello?fail="hello"

Here's how X-Ray look like

![image](https://user-images.githubusercontent.com/3340292/111505036-7da08900-8748-11eb-9035-3727c2aed158.png)

![image](https://user-images.githubusercontent.com/3340292/111505070-88f3b480-8748-11eb-9734-09be0c7803f5.png)

**Comment by pcolazurdo** [comment] 2021-03-17 23:41
@heitorlessa The issue seems to be specfic about how xray-sdk patches the boto functions. As it is today all exceptions will be [captured in the API response meta_processor](https://github.com/aws/aws-xray-sdk-python/blob/508f929fee495710656c0c1478f8873a2e9e5666/aws_xray_sdk/ext/boto_utils.py#L63) 

@latacora-tomekr from a purist point of view, IMHO, xray seems to be doing the expected thing; boto is returning an exception so this is captured at the boto3 subsegment, even if it is handled later in the call chain you will still like to see this (i.e. exception handling may take some extra milliseconds compared with a non exception one) - I suppose there may be some cases where filtering which exceptions to trace may become useful, but I think the cost of maintaining that will be extra hard. On the other hand, not sure an empty secret should be returning a ResourceNotFound exception. I've created [an issue in boto3 for reference](https://github.com/boto/boto3/issues/2794)

**Comment by heitorlessa** [comment] 2021-03-18 10:36
As @pcolazurdo correctly pointed out, that exception recording isn't coming from the SubsegmentContextManager but from Boto metaprocessor. Because it's part of the patch, the only way to get rid of that is by having X-Ray to create a feature toggle here: https://github.com/aws/aws-xray-sdk-python/blob/508f929fee495710656c0c1478f8873a2e9e5666/aws_xray_sdk/ext/boto_utils.py#L73

That aside, I took time to reproduce different scenarios to understand whether that produces inaccurate vs informational results -- Turns out it's the latter.

When handling the ClientError exception from boto the final status of that trace remains Green, so I concur with Pablo that I don't see that as an issue

![image](https://user-images.githubusercontent.com/3340292/111610864-17fddc80-87dc-11eb-857d-d93cd4fa09db.png)

When an exception is unhandled however, it's clear that the status is accurate

![image](https://user-images.githubusercontent.com/3340292/111611011-467bb780-87dc-11eb-8633-68f0030a0227.png)

I'm removing the `bug` label as it's the intended behaviour, but keeping this open to hear what you'd like to do. If X-Ray team in that issue upstream think is valid, and would be okay with a feature flag, I'd be happy to contribute that to them as a courtesy.

**Comment by latacora-tomekr** [comment] 2021-03-22 15:26
Yea I wonder if this is an issue specifically with the way the secretsmanager calls are handled since boto3 will throw a `botocore.errorfactory.ResourceNotFoundException` exception instead of something like a ClientError. Thanks for opening the issue @pcolazurdo

**Comment by heitorlessa** [comment] 2021-03-29 16:03
hey @latacora-tomekr I'm gonna close this as I believe boto can handle the Exception better, and X-Ray doesn't seem to be at fault here as we agreed - Please let me know otherwise ;-)

**Closed by heitorlessa** 2021-03-29 16:03 UTC
Labels: area/tracer, status/pending-information
